omp_hello:
	 gcc -g -Wall -fopenmp -o omp_hello omp_hello.c

bubble:
	 gcc -g -Wall -fopenmp -o bubble bubble.c 

mat_vect_mult:
	 gcc -g -Wall -fopenmp -o mat_vect_mult mat_vect_mult.c

odd_even:
	gcc -g -Wall -fopenmp -o odd_even odd_even.c

omp_fibo:
	gcc -g -Wall -fopenmp -o omp_fibo omp_fibo.c

omp_hello_err_chk:
	gcc -g -Wall -fopenmp -o omp_hello_err_chk omp_hello_err_chk.c

omp_mat_vect:
	gcc -g -Wall -fopenmp -o omp_mat_vect omp_mat_vect.c

omp_mat_vect_rand_split:
gcc -g -Wall -fopenmp -o omp_mat_vect omp_mat_vect.c

odd_even1:
	gcc -g -Wall -fopenmp -o odd_even1 odd_even1.c

